# Generated by Django 5.2.3 on 2025-06-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riotapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='tag_name',
            new_name='tag_line',
        ),
    ]
