# Generated by Django 5.2.3 on 2025-06-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riotapi', '0002_rename_tag_name_account_tag_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
