# Generated by Django 5.2.3 on 2025-06-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riotapi', '0003_alter_matchhistory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
